version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
